default:
	gcc hilosopher_two_sauce_ball_semaphore.c -o hilosopher_two_sauce_ball_semaphore.o lpthread -lrt
	gcc philosopher_two_sauce_ball_strict.c -o philosopher_two_sauce_ball_strict.o -lphread -lrt
	